# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2024 - 2025 The MathWorks, Inc.

name: CI using MATLAB

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  schedule:
    - cron:  '55/61 20/25 1/6 * *' # schedule a weekly-ish build

jobs:

  job-check-project:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
          cache: true
          products: |
            Simulink
            Simscape
            Simscape_Driveline
            Simscape_Electrical
            Simscape_Multibody
            MATLAB_Test

      - name: Run tests
        uses: matlab-actions/run-command@v2
        with:
          command: openProject(pwd); TestRunnerCartesianRobot;